export default [
  {
    name: 'icons-carbon',
    display: 'Carbon',
    icons: {
      'codicon:files': 'carbon:folder',
      'codicon:search': 'carbon:search',
      'codicon:scm': 'carbon:branch',
      'codicon:debug': 'carbon:debug',
      'codicon:extensions': 'carbon:container-software',
      'codicon:person': 'carbon:settings-adjust',
      'codicon:settings': 'carbon:settings-adjust',
      'codicon:new-file': 'carbon:new-tab',
      'codicon:new-folder': 'carbon:folder-add',
      'codicon:refresh': 'carbon:restart',
      'codicon:collapse-all': 'carbon:minimize',
      'codicon:editor-layout': 'carbon:transpose',
      'codicon:save': 'carbon:save',
      'codicon:cancel': 'carbon:close',
      'codicon:split-horizontal': 'carbon:open-panel-right',
      'codicon:split-vertical': 'carbon:open-panel-bottom',
      'codicon:error': 'carbon:error',
      'codicon:compare-changes': 'carbon:compare',
      'codicon:clear-all': 'carbon:clean',
      'codicon:warning': 'carbon:warning-alt',
      'codicon:bell': 'carbon:chat',
      'codicon:sync': 'carbon:renew',
      'codicon:lightbulb': 'carbon:idea',
      'codicon:filter': 'carbon:filter',
      'codicon:gear': 'carbon:settings',
      'codicon:play': 'carbon:play',
      'codicon:stop': 'carbon:stop',
      'codicon:debug-restart': 'carbon:restart',
      'codicon:debug-disconnect': '',
      'codicon:debug-step-in': 'mdi:debug-step-into',
      'codicon:debug-step-out': '',
      'codicon:debug-step-back': '',
      'codicon:debug-step-over': '',
      'codicon:debug-pause': 'carbon:pause',
      'codicon:debug-continue': '',
      'codicon:debug-reverse-continue': '',
      'codicon:trash': 'carbon:delete',
      'codicon:add': 'carbon:add',
      'codicon:close-all': 'carbon:close-outline',
      'codicon:activate-breakpoints': 'carbon:boolean',
      'codicon:remote-explorer': 'carbon:cloud-ceiling',
      'codicon:symbol-constructor': 'carbon:cube',
      'codicon:symbol-event': 'carbon:flash',
      'codicon:symbol-variable': 'carbon:3d-mpr-toggle',
      'codicon:remote': '',
    },
  },
]
